// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARpOCzzqZsXW61FUVbkeINqj_R7JxH9iA',
    appId: '1:719600442713:web:a5f701e0ab66ee244b4048',
    messagingSenderId: '719600442713',
    projectId: 'dicendestiny-c20c7',
    authDomain: 'dicendestiny-c20c7.firebaseapp.com',
    storageBucket: 'dicendestiny-c20c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ1hzopffSod3tp0pynr_mEDBQs_Jt2-s',
    appId: '1:719600442713:android:b3cccde5282182424b4048',
    messagingSenderId: '719600442713',
    projectId: 'dicendestiny-c20c7',
    storageBucket: 'dicendestiny-c20c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0qrtJT_g4atBLFqOXWwBLiViZPgh9oDw',
    appId: '1:719600442713:ios:1eaa6f5848c9204e4b4048',
    messagingSenderId: '719600442713',
    projectId: 'dicendestiny-c20c7',
    storageBucket: 'dicendestiny-c20c7.appspot.com',
    iosBundleId: 'com.example.diceanddestiny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0qrtJT_g4atBLFqOXWwBLiViZPgh9oDw',
    appId: '1:719600442713:ios:14426a7272bbe0954b4048',
    messagingSenderId: '719600442713',
    projectId: 'dicendestiny-c20c7',
    storageBucket: 'dicendestiny-c20c7.appspot.com',
    iosBundleId: 'com.example.diceanddestiny.RunnerTests',
  );
}
