// ignore_for_file: non_constant_identifier_names

import 'dart:math';

List<String> PEOPLE = [
  'aasimar',
  'aarakocra',
  'dragonborn',
  'drow',
  'duergar',
  'hill dwarf',
  'mountain dwarf',
  'high elf',
  'wood elf',
  'firbolg',
  'genasi',
  'gnome',
  'deep gnome',
  'goliath',
  'half-elf',
  'half-Orc',
  'halfling',
  'human',
  'kenku',
  'kobold',
  'lizardfolk',
  'tabaxi',
  'tiefling'
];

List<String> ANIMALS = [
  'cow',
  'sheep',
  'pig',
  'owl bear',
  'elk',
  'moose',
  'jaguar',
  'giant spider',
  'black bear',
  'Hippogriff',
  'wolf',
  'unicorn',
  'pony',
  'pegasus',
  'merrow',
  'death dog',
  'cockatrice'
];

List<String> MONSTER = [
  'bugbear',
  'bullywug',
  'gibberling',
  'goblin',
  'hobgoblin',
  'orc',
  'orog',
  'Awakened Shrub',
  'Cranium Rat',
  'Homunculus',
  'Shrieker',
  'Giant Crab',
  'Giant Rat',
  'Giant Weasel',
  'giant fire beetle',
  'Manes',
  'Monodrone',
  'Twig Blight',
  'Xvart',
  'Dimetrodon',
  'Dretch',
  'Duodrone',
  'Giant Badger',
  'Giant Bat',
  'Giant Centipede',
  'Giant Frog Medium',
  'Giant Lizard',
  'Giant Owl',
  'Giant Poisonous Snake',
  'Giant Wolf Spider',
  'Grimlock',
  'Grung',
  'grizzly bear',
  'Mud Mephit',
  'Needle Blight',
  'Rothe',
  'Skeleton',
  'Smoke Mephit',
  'Steam Mephit',
  'Troglodyte',
  'Black Bear',
  'Chitine',
  'Cockatrice',
  'Crocodile',
  'Darkling',
  'Darkmantle',
  'Dust Mephit',
  'Firenewt',
  'Gazer',
  'Giant Goat',
  'Giant Wasp',
  'Gnoll',
  'Gray Ooze',
  'Ice Mephit',
  'Magma Mephit',
  'Magmin',
  'Rust monster',
  'Sahuagin',
  'Shadow',
  'Vine blight',
  'Warhorse',
  'Worg',
  'Brown Bear',
  'Death Dog',
  'Dire Wolf',
  'Fire Snake',
  'Ghoul',
  'Giant Eagle',
  'Giant Spider',
  'Giant Strider',
  'Giant Toad',
  'Giant Vulture',
  'Harpy Medium',
  'Hippogriff',
  'Imp',
  'Maw Demon',
  'Nilbog',
  'Quadrone',
  'Quasit',
  'Quickling',
  'Scarecrow',
  'Specter',
  'Thri-kreen',
  'Vargouille',
  'Yuan-ti Pureblood',
  'Ankheg',
  'Aurochs',
  'Awakened Tree',
  'Azer',
  'Black Dragon Wyrmling',
  'Carrion Crawler',
  'Cave Bear',
  'Centaur',
  'Ettercap',
  'Gargoyle',
  'Gelatinous Cube',
  'Ghast',
  'Giant Boar',
  'Giant Constrictor Snake',
  'Giant Elk',
  'Gibbering Mouther',
  'Githzerai',
  'Gnoll',
  'Green Dragon Wyrmling',
  'Grick',
  'Grung',
  'Intellect Devourer',
  'Meenlock',
  'Merrow',
  'Mimic',
  'Minotaur',
  'Ochre',
  'Ogre',
  'Pentadrone',
  'Polar Bear',
  'Quetzalcoatlus',
  'Saber-toothed Tiger',
  'Sea Hag',
  'Shadow Mastiff',
  'Specter',
  'Spined Devil',
  'Wererat',
  'White Dragon Wyrmling',
  'Will-o-wisp',
  'Basilisk',
  'Bearded Devil',
  'Blue Dragon Wyrmling',
  'Cave Fisher',
  'Choldrith',
  'Displacer Beast',
  'Doppelganger',
  'flail snail',
  'giant scorpion',
  'green hag',
  'grell',
  'hell Hound',
  'hook Horror',
  'manticore',
  'minotaur',
  'nightmare',
  'owlbear',
  'quaggoth',
  'redcap',
  'slithering',
  'spectator',
  'trapper',
  'water weird',
  'werewolf',
  'wight'
];

String getEvent() {
  var events = [
    '${diceRoll(6)} hostile ${replPEOPLE("HUMANOID")} cultists of a dark god in black cloaks.',
    '${diceRoll(6)} non-hostile ${replPEOPLE("HUMANOID")} cultists in black cloaks.',
    '${diceRoll(6)} ${replMONSTER("MONSTER")}s in black cloaks trying to travel peacefully.',
    '${diceRoll(6)} wondering magic-item merchants in black cloaks.',
    '${diceRoll(6)} terror-stricken ${replPEOPLE("HUMANOID")} peasants in black cloaks.',
    '${diceRoll(6)} ${replPEOPLE("HUMANOID")} travelers who really, really like black cloaks.',
    'Merchant caravan of ${diceRoll(8)} merchants.',
    '${diceRoll(6)} peasant traders.',
    'Prison transport with ${diceRoll(12)} ${replPEOPLE("HUMANOID")} prisoners, and ${diceRoll(8)} ${replPEOPLE("HUMANOID")} guards.',
    '${replPEOPLE("HUMANOID")} military Caravan.',
    'Traveling ${replPEOPLE("HUMANOID")} entertainers.',
    'Nomadic tribe of ${diceRoll(10)} ${replPEOPLE("HUMANOID")}s.',
    'Military troupe of ${((diceRoll(6) * 4) + 5)} ${replPEOPLE("HUMANOID")}.',
    '${((diceRoll(6) * 3) + 5)} ${replPEOPLE("HUMANOID")} bandits.',
    '${((diceRoll(6) * 4) + 5)} ${replPEOPLE("HUMANOID")} bandits.',
    '${((diceRoll(6) * 1) + 3)} ${replPEOPLE("HUMANOID")} bandits.',
    '${((diceRoll(6) * 2) + 2)} ${replPEOPLE("HUMANOID")} bandits.',
    '${((diceRoll(6) * 4) + 5)} hostile ${replMONSTER("MONSTER")}s.',
    '${((diceRoll(6) * 4) + 3)} hostile ${replMONSTER("MONSTER")}s.',
    '${((diceRoll(6) * 3) + 4)} hostile ${replMONSTER("MONSTER")}s.',
    '${((diceRoll(6) * 3) + 5)} hostile ${replMONSTER("MONSTER")}s.',
    '${((diceRoll(6) * 2) + 4)} hostile ${replMONSTER("MONSTER")}s.',
    '${((diceRoll(6) * 2) + 3)} hostile ${replMONSTER("MONSTER")}s.',
    '${((diceRoll(6) * 3) + 2)} hostile ${replMONSTER("MONSTER")}s.',
    '${((diceRoll(6) * 2) + 2)} hostile ${replMONSTER("MONSTER")}s.',
    '${((diceRoll(6) * 4) + 5)} ${replPEOPLE("HUMANOID")} refugees.',
    'Military patrol of ${diceRoll(10) + 2} ${replPEOPLE("HUMANOID")}.',
    '${diceRoll(10) + 2} ${replPEOPLE("HUMANOID")} highwaymen.',
    '${diceRoll(10) + 2} defeated ${replPEOPLE("HUMANOID")} bandits.',
    '${diceRoll(10) + 2} ${replMONSTER("MONSTER")}s.',
    'A ${replPEOPLE("HUMANOID")} survivor of an attack.',
    'A ${replPEOPLE("HUMANOID")} scout.',
    'A ${replPEOPLE("HUMANOID")} con man.',
    'A ${replPEOPLE("HUMANOID")} hermit.',
    'An old and weary ${replPEOPLE("HUMANOID")} who asks if they can share the party’s fire in exchange for a tale, but it\'s a trap!',
    'An old and weary ${replPEOPLE("HUMANOID")} who asks if they can share the party’s fire in exchange for a tale who is actually trying to flee from the law.',
    'An old and weary ${replPEOPLE("HUMANOID")} who asks if they can share the party’s fire in exchange for a tale. He is trying to get a family heirloom to a nearby city (25% chance he dies in his sleep).',
    'A old and weary ${replPEOPLE("HUMANOID")} who asks if they can share the party’s fire in exchange for a tale.',
    'A tree covered in thick chains; someone really hates that tree.',
    'A tree covered in thick chains; it is an ent just wants to be free and left alone.',
    'A tree covered in thick chains; it is an evil ent.',
    'A tree covered in thick chains; the tree is sealing an evil power.',
    'A wounded and suffering ANIMAL. 50% chance it will die.',
    'A wounded ${replPEOPLE("HUMANOID")} who just asks for them to end their life.',
    'A wounded ${replMONSTER("MONSTER")} that fears for its life.',
    'A wounded ${replPEOPLE("HUMANOID")} soldier.',
    'A lone shack housing a hospitable old ${replPEOPLE("HUMANOID")} widow.',
    'A lone shack housing a ${replPEOPLE("HUMANOID")} man who brews a potent ale.',
    'A lone shack housing a simple family of ${replPEOPLE("HUMANOID")}s.',
    'A lone shack housing a friendly ${replPEOPLE("HUMANOID")} witch.',
    'Another adventuring party with ${diceRoll(12)} members who are hostile with any provocation.',
    'Another adventuring party with ${diceRoll(12)} members who are friendly.',
    'Another adventuring party with ${diceRoll(12)} members who have a prisoner.',
    'Another adventuring party with ${diceRoll(12)} members who would like to share a fire.',
    'Another adventuring party with ${diceRoll(12)} members who are higher level than the party.',
    'Another adventuring party with ${diceRoll(12)} members who are complete and utter noobs.',
    'A small village of ${replPEOPLE("HUMANOID")} that is under attack.',
    'A small village of ${replPEOPLE("HUMANOID")}s that is afflicted by a deadly plague.',
    'A small village of ${replPEOPLE("HUMANOID")}s that is afflicted by a mysterious curse.',
    'A small village of ${replPEOPLE("HUMANOID")}s that is afflicted by famine.',
    'A small village of ${replPEOPLE("HUMANOID")}s.',
    'A small village of ${replPEOPLE("HUMANOID")}s having a festival.',
    'A herd of ${((diceRoll(6) * 4) + 5)} ANIMALs; but it\'s a trap!',
    'A herd of ${((diceRoll(6) * 4) + 5)} domesticated ANIMALs, just passing through.',
    'A herd of ${((diceRoll(6) * 4) + 5)} ANIMALs that are out of control.',
    'A herd of ${((diceRoll(6) * 4) + 5)} lost ANIMALs',
    'A herd of ${((diceRoll(6) * 4) + 5)} wild and dangerous ANIMALs.',
    'A herd of ${((diceRoll(6) * 4) + 5)} ANIMALs; their shepherd was killed and the herd is being stolen.',
    '${replPEOPLE("HUMANOID")} military checkpoint looking for missing prisoners.',
    '${replPEOPLE("HUMANOID")} military checkpoint trying to deter the high bandit activity in the area.',
    '${replPEOPLE("HUMANOID")} military checkpoint conscripting passersby.',
    '${replPEOPLE("HUMANOID")} military checkpoint looking for a valuable stolen artifact.',
    '${replPEOPLE("HUMANOID")} bandit outpost demanding a toll.',
    'A checkpoint that has been overrun with ${diceRoll(12)} ${replMONSTER("MONSTER")}s.',
    'An outpost of ${replMONSTER("MONSTER")}s looking for a kidnapped child.',
    'An outpost of ${replMONSTER("MONSTER")}s demanding food.',
    'An outpost of ${replMONSTER("MONSTER")}s demanding a toll.',
    '${(diceRoll(6) * 4) + 5} hostile MONSTERs.',
    '${(diceRoll(6) * 4) + 3} hostile MONSTERs.',
    '${(diceRoll(6) * 3) + 4} hostile MONSTERs.',
    '${(diceRoll(6) * 3) + 5} hostile MONSTERs.',
    '${(diceRoll(6) * 2) + 4} hostile MONSTERs.',
    '${(diceRoll(6) * 2) + 3} hostile MONSTERs.',
    '${(diceRoll(6) * 3) + 2} hostile MONSTERs.',
    '${(diceRoll(6) * 2) + 2} hostile MONSTERs.',
    '${(diceRoll(6) * 4) + 5} HUMANOID refugees.',
    'Military patrol of ${diceRoll(10) + 2} HUMANOID.',
    '${diceRoll(10) + 2} HUMANOID highwaymen.',
    '${diceRoll(10) + 2} defeated HUMANOID bandits.',
    '${diceRoll(10) + 2} MONSTERs.',
    'A HUMANOID survivor of an attack.',
    'A HUMANOID scout.',
    'A HUMANOID con man.',
    'A HUMANOID hermit.',
    'An old and weary HUMANOID who asks if they can share the party’s fire in exchange for a tale, but it\'s a trap!',
    'An old and weary HUMANOID who asks if they can share the party’s fire in exchange for a tale who is actually trying to flee from the law.',
    'An old and weary HUMANOID who asks if they can share the party’s fire in exchange for a tale. He is trying to get a family heirloom to a nearby city (25% chance he dies in his sleep).',
    'A old and weary HUMANOID who asks if they can share the party’s fire in exchange for a tale.',
    'A tree covered in thick chains; someone really hates that tree.',
    'A tree covered in thick chains; it is an ent just wants to be free and left alone.',
    'A tree covered in thick chains; it is an evil ent.',
    'A tree covered in thick chains; the tree is sealing an evil power.',
    'A wounded and suffering ANIMAL. 50% chance it will die.',
    'A wounded HUMANOID who just asks for them to end their life.',
    'A wounded MONSTER that fears for its life.',
    'A wounded HUMANOID soldier.',
    'A lone shack housing a hospitable old HUMANOID widow.',
    'A lone shack housing a HUMANOID man who brews a potent ale.',
    'A lone shack housing a simple family of HUMANOIDs.',
    'A lone shack housing a friendly HUMANOID witch.',
    'Another adventuring party with ${diceRoll(12)} members who are hostile with any provocation.',
    'Another adventuring party with ${diceRoll(12)} members who are friendly.',
    'Another adventuring party with ${diceRoll(12)} members who have a prisoner.',
    'Another adventuring party with ${diceRoll(12)} members who would like to share a fire.',
    'Another adventuring party with ${diceRoll(12)} members who are higher level than the party.',
    'Another adventuring party with ${diceRoll(12)} members who are complete and utter noobs.',
    'A small village of HUMANOID that is under attack.',
    'A small village of HUMANOIDs that is afflicted by a deadly plague.',
    'A small village of HUMANOIDs that is afflicted by a mysterious curse.',
    'A small village of HUMANOIDs that is afflicted by famine.',
    'A small village of HUMANOIDs.',
    'A small village of HUMANOIDs having a festival.',
    'A herd of ${(diceRoll(6) * 4) + 5} ANIMALs; but it\'s a trap!',
    'A herd of ${(diceRoll(6) * 4) + 5} domesticated ANIMALs, just passing through.',
    'A herd of ${(diceRoll(6) * 4) + 5} ANIMALs that are out of control.',
    'A herd of ${(diceRoll(6) * 4) + 5} lost ANIMALs',
    'A herd of ${(diceRoll(6) * 4) + 5} wild and dangerous ANIMALs.',
    'A herd of ${(diceRoll(6) * 4) + 5} ANIMALs; their shepherd was killed and the herd is being stolen.',
    'A HUMANOID military checkpoint looking for missing prisoners.',
    'A HUMANOID military checkpoint trying to deter the high bandit activity in the area.',
    'A HUMANOID military checkpoint conscripting passersby.',
    'A HUMANOID military checkpoint looking for a valuable stolen artifact.',
    'A HUMANOID bandit outpost demanding a toll.',
    'A checkpoint that has been overrun with ${diceRoll(12)} MONSTERs.',
    'An outpost of MONSTERs looking for a kidnapped child.',
    'An outpost of MONSTERs demanding food.',
    'An outpost of MONSTERs demanding a toll.',
    'An outpost of MONSTERs warning of the road ahead.',
    'A crazy old HUMANOID hermit who constructed his own outpost in the middle of the road.',
    'A traveling HUMANOID brewer that makes the best ale.',
    'A traveling HUMANOID brewer that makes the best mead.',
    'A traveling HUMANOID brewer that makes the best rum.',
    'A traveling HUMANOID brewer that makes the best coffee.',
    'A traveling HUMANOID alchemist.',
    'A traveling HUMANOID brewer that makes the worst ale.',
    'A traveling HUMANOID brewer that makes the worst mead.',
    'A traveling HUMANOID brewer that makes the worst rum.',
    'A traveling HUMANOID brewer that makes the worst coffee.',
    'A traveling HUMANOID brewer called the Brewmaster, his quest is to bring ale to the lands of the free.',
    'A black dragon that ignores party and flies overhead.',
    'A gold dragon that offers advice.',
    'A silver dragon looking for the best joke.',
    'A red dragon that demands payment to pass it.',
    'A dragon that gives the party a warning.',
    'A dragon that eats the nearest ANIMAL.',
    'A wounded dragon.',
    'A dragon battle.',
    'A hostile dragon.',
    'A HUMANOID hunter that has too much game.',
    'A starving HUMANOID hunter.',
    'A HUMANOID hunter that needs help.',
    'A lonely HUMANOID hunter that just wants a little bit of company.',
    'A pair of HUMANOID that asks the party for test subjects.',
    'A pair of HUMANOID that are testing mech.',
    'A pair of HUMANOID that are gathering samples.',
    'A bickering HUMANOID couple.',
     'A pair of HUMANOID that asks the party for test subjects.',
    'A pair of HUMANOID that are testing mech.',
    'A pair of HUMANOID that are gathering samples.',
    'A bickering HUMANOID couple.',
    'A traveling HUMANOID bard that is trying to gather and share tales.',
    'A HUMANOID bard that travels with the party for a time.',
    'A traveling HUMANOID bard that is trying to steal valuables.',
    'A traveling HUMANOID bard that has a cursed instrument.',
    'A very busy HUMANOID wizard racing down the road.',
    'A HUMANOID wizard being chased down the road.',
    'An insane HUMANOID wizard running down the road.',
    'A HUMANOID wizard running down the road who stops and asks the party for directions to a place they have never heard of.',
    'A HUMANOID wizard running down the road who is very, very lost.',
    'A HUMANOID wizard running down the road who is just enjoying a nice run.',
    'A HUMANOID wearing a mask and full robes riding a skeletal horse who rides past the party.',
    'A HUMANOID wearing a mask and full robes riding a skeletal horse who asks for directions.',
    'A HUMANOID wearing a mask and full robes riding a skeletal horse who is looking for someone.',
    'A HUMANOID wearing a mask and full robes riding a skeletal horse who carries a message of the highest importance for one of the party members.'
  ];

  var val = (diceRoll(events.length) - 1);

  return replAll(events[val]);
}

String replAll(String event) {
  event = replANIMAL(event);
  event = replMONSTER(event);
  event = replPEOPLE(event);
  return event;
}

String replANIMAL(String str) {
  var val = (diceRoll(ANIMALS.length) - 1);
  return str.replaceAll('ANIMAL', ANIMALS[val]);
}

String replMONSTER(String str) {
  var val = (diceRoll(MONSTER.length) - 1);
  return str.replaceAll('MONSTER', MONSTER[val]);
}

String replPEOPLE(String str) {
  var val = (diceRoll(PEOPLE.length) - 1);
  return str.replaceAll('HUMANOID', PEOPLE[val]);
}

int diceRoll(int x) {
  return (1 + (Random().nextInt(x)));
}